---
title: "R Notebook"
output: html_notebook
---

# Comparing fold-changes


```{r}
suppressPackageStartupMessages({
  library("Seurat")
  library("splattdr")
  library("splatter")
  library("ggplot2")
  library("ggpubr")
  library("dplyr")
  library("scater")
  library("factoextra")
})
```


```{r eval=FALSE}
real.data = readRDS('/mnt/home/naultran/SNSEQDATA_FINAL/GSE148339_liver.integrated.final.RData') #Change to DR Dataset
unique.celltypes = unique(real.data$celltype)
real.sce <- as.SingleCellExperiment(real.data)
colData(real.sce)$Dose <- ifelse(colData(real.sce)$treatment == 'CONTROL', 0, 30)
dose_vec = sort(unique(colData(real.sce)$Dose)
```

```{r eval = FALSE}
real.data = readRDS('/mnt/home/naultran/SNSEQDATA_FINAL/Zacharewski.tcdd.snseq.doseresponse.011321.RData') #Change to DR Dataset
colnames(real.data@meta.data)[107] = 'celltype'
unique.celltypes = unique(real.data$celltype)
real.sce <- as.SingleCellExperiment(real.data)
dose_vec = sort(unique(colData(real.sce)$Dose)
```

```{r}
real.fc <- list()
for (ct in unique.celltypes[1:10]){
  sce  <- real.sce[,which(colData(real.sce)$celltype == ct)]
  foldChange <- calcFC(sce)
  foldChange$celltype <- ct
  real.fc[[ct]] <- foldChange
}
real.fc.table <- do.call('rbind', real.fc)
real.fc.table$dataset <- 'real'
colnames(real.fc.table) <- gsub('fc..dose..', 'calculatedFC30', colnames(real.fc.table))
```


```{r fig.width = 14, fig.height = 4}
ggplot(data = real.fc.table, aes(x = calculatedFC30, color = celltype)) +
  geom_density(size = 1.1) + 
  theme_bw()
```

```{r}
sim.dose = c(0, 0.01, 0.03, 0.1, 0.3, 1, 3, 10, 30)
dose.prob = rep(1/9, 9)
data(params)
params@nGenes = 2000
params@nBatches = length(sim.dose)*3
params@batch.facLoc = rep(0.1, params@nBatches)
params@batch.facScale = rep(0.1, params@nBatches)
params@nCells = 500*9

par.opts <- list()
for (facLoc in c(-1, -0.5, -0.2, 0, 0.2, 0.5, 1)){
  for (facScale in c(0, 0.2, 0.5, 1, 1.5)){
    for (probDown in c(0.1, 0.5, 0.9)){
      for (probDE in c(0.05, 0.1, 0.25)){
        name <- paste0(facLoc, '_', facScale, '_', probDown, '_', probDE)
        print(name)
        # Define doses and number of cells per dose
        
        params@de.facLoc = facLoc
        params@de.facScale = facScale
        params@de.downProb = probDown
        params@de.prob = probDE
        
        # Simulate dose response data from parameter estimates
        sim = splatSimulateDR(params, dose.names = sim.dose, dose.prob = dose.prob, lib.scale = 1, verbose = FALSE)
        foldChange <- calcFC(sim)
        foldChange$celltype <- name
        par.opts[[name]] <- foldChange
      }
    }
  }
}

par.opts.table <- do.call('rbind', par.opts)
par.opts.table$dataset = par.opts.table$celltype
```

```{r fig.height = 24, fig.width = 24}
real.subsampled <- real.fc.table[sample(1:nrow(fc.table), params@nGenes),]
real.subsampled.fc <- real.subsampled[ , 'calculatedFC30', drop = FALSE]

ggplot(data = par.opts.table, aes(x = calculatedFC30)) +
  facet_wrap(.~celltype) +
  ylim(c(0,10)) +
  geom_density(size = 1.2, alpha = 0.8) + 
  geom_density(data = real.subsampled.fc, aes(calculatedFC30), color = 'red', fill = 'red', size = 1, alpha = 0.2) +
  theme_bw()
```

```{r}
combined.table <- data.frame(
  dataset = c(real.fc.table$dataset, par.opts.table$dataset),
  calculatedFC30 = c(real.fc.table$calculatedFC30, par.opts.table$calculatedFC30)
)

summary.df <- combined.table %>% group_by(dataset) %>% summarize(mean = mean(calculatedFC30), median = median(calculatedFC30), min = min(calculatedFC30), max = max(calculatedFC30), sd = sd(calculatedFC30)) %>% select(mean, median, min, max, sd)
rownames(summary.df) <- unique(combined.table$dataset)

ks.test.map <- combined.table %>% group_by(dataset) %>% group_map(~ ks.test(real.subsampled.fc, .x$calculatedFC30))
```

```{r}
par.hc <- eclust(summary.df, "hclust") # compute hclust
par.km <- eclust(summary.df, "kmeans", nstart = 20)
```



