---
title: "R Notebook"
output: html_notebook
---

## Setting up the environment and displaying session information for reproducibility
```{r}
library(doParallel, quietly = TRUE)
library(dplyr, quietly = TRUE)
library(ggplot2, quietly = TRUE)
library(Seurat, quietly = TRUE)
library(scater, quietly = TRUE)
library(SingleCellExperiment, quietly = TRUE)
library(splatter, quietly = TRUE)
source_path = 'C:\\Users\\15177\\OneDrive - Michigan State University\\Documents\\Projects\\Prj161-snSeq-Mm_TCDD_DR_Sept2019\\snSeq-DGE\\R\\simulation_functions.R'
source('../R/dose_response_models.R')
source(source_path)
source('~/CodeSnippets/splatter/R/splat-simulate.R')
source('~/Projects/Prj161-snSeq-Mm_TCDD_DR_Sept2019/snSeq-DGE/R/splatterWrapper.R')
source('~/Projects/Prj161-snSeq-Mm_TCDD_DR_Sept2019/snSeq-DGE/R/simulation_functions_splatter.R')
sessionInfo()
memory.limit(size = 64000)
```

# Estimate Splat parameters from each dose group of the hepatocyte cluster
```{r}
liv.dr.clust1 = readRDS('C:\\Users\\15177\\Downloads\\HPC-TempDownload\\FULL-TEMPORARY\\clust1.RData')
params.list = list()
for (d in unique(liv.dr.clust1$Dose)[1]){
  liv = subset(liv.dr.clust1, subset = Dose == d)
  sce = as.SingleCellExperiment(liv)
  counts = as.matrix(counts(sce))
  params.list[[paste(d, sep='')]] = splatEstimate(counts)
}
```

# Begin simulation of dose-response data
## Choose and set base splatter parameters object to initiate simulation
```{r}
params = params.list[[1]] #Dose 0

#params@nGenes = 15000
params@nCells = 500 * 9
params@de.prob = 0.1
params@de.facLoc = 3
params@de.facScale = 0.8
dose.names = c(0, 0.01, 0.03, 0.1, 0.3, 1, 3, 10, 30)
dose.prob = rep(1/9, length(dose.names))
```

```{r}
simDR = splatSimulateDR(params, method = 'doseresp', dose.names = dose.names, dose.prob = dose.prob)
```

Compile summary statistics for comparison
```{r}
gene.summary = data.frame(Dataset = character(), Dose = factor(), mean = double(), var = double(), p.zero = double())
for (d in dose.names){
  sub.exp.mat = assays(simDR)$logcount[,which(colData(simDR)$Dose == d)]
  mean.vec = apply(sub.exp.mat, 1, function(x) mean(x))
  var.vec = apply(sub.exp.mat, 1, function(x) var(x))
  p.zero.vec = apply(sub.exp.mat, 1, function(x) length(x[which(x == 0)])/length(x))
  temp.df = data.frame(Dataset = 'SplattDR', Dose = d, mean = mean.vec, var = var.vec, p.zero = p.zero.vec)
  gene.summary = rbind(gene.summary, temp.df)
}

for (d in dose.names){
  sub.exp.mat = as.matrix(liv.dr.clust1@assays$RNA@data[,which(liv.dr.clust1$Dose == d)])
  mean.vec = apply(sub.exp.mat, 1, function(x) mean(x))
  var.vec = apply(sub.exp.mat, 1, function(x) var(x))
  p.zero.vec = apply(sub.exp.mat, 1, function(x) length(x[which(x == 0)])/length(x))
  temp.df = data.frame(Dataset = 'Real', Dose = d, mean = mean.vec, var = var.vec, p.zero = p.zero.vec)
  gene.summary = rbind(gene.summary, temp.df)
}

cell.summary = data.frame(Dataset = character(), mean = double(), var = double(), p.zero = double())
sub.exp.mat = assays(simDR)$logcount
mean.vec = apply(sub.exp.mat, 2, function(x) mean(x))
var.vec = apply(sub.exp.mat, 2, function(x) var(x))
p.zero.vec = apply(sub.exp.mat, 2, function(x) length(x[which(x == 0)])/length(x))
temp.df = data.frame(Dataset = 'SplattDR', mean = mean.vec, var = var.vec, p.zero = p.zero.vec)
cell.summary = rbind(cell.summary, temp.df)

sub.exp.mat = as.matrix(liv.dr.clust1@assays$RNA@data)
mean.vec = apply(sub.exp.mat, 2, function(x) mean(x))
var.vec = apply(sub.exp.mat, 2, function(x) var(x))
p.zero.vec = apply(sub.exp.mat, 2, function(x) length(x[which(x == 0)])/length(x))
temp.df = data.frame(Dataset = 'Real', mean = mean.vec, var = var.vec, p.zero = p.zero.vec)
cell.summary = rbind(cell.summary, temp.df)
```

```{r fig.width = 18, fig.height = 6}
F1.A = ggplot(data = gene.summary, aes(x = factor(Dose), y = mean, color = Dataset)) + 
  geom_boxplot() +
  theme_bw()

F1.B = ggplot(data = gene.summary, aes(x = factor(Dose), y = var, color = Dataset)) + 
  geom_boxplot() +
  theme_bw()

F1.C = ggplot(data = gene.summary, aes(x = factor(Dose), y = p.zero, color = Dataset)) +
  geom_boxplot() +
  #geom_smooth() +
  theme_bw()

F1.D = ggplot(data = gene.summary, aes(x = mean, y = var, color = Dataset)) +
  geom_point(size = 0.7, alpha = 0.3) +
  #geom_smooth() +
  theme_bw()

F1.E = ggplot(data = cell.summary, aes(x = Dataset, y = p.zero)) +
  geom_boxplot() +
  #geom_smooth() +
  theme_bw()

figure = ggpubr::ggarrange(F1.A, F1.B, F1.C, F1.D, F1.E, labels = c("A","B","C", "D", "E"), ncol = 3, nrow = 2)
figure
```
```{r}
simDR = runPCA(simDR)
plotPCA(simDR, colour_by = "Dose")
```




```{r fig.width = 12, fig.height = 8}
colors = c('Splatter Simulation' = 'red', 'Real Data' = 'blue', 'In-house Simulation' = 'green')

P1 = ggplot(data = realData, aes(x = mean, y = percent_zero)) +
  geom_point(aes(color = 'Real Data'), alpha = 0.08, size = 0.5) +
  geom_point(data = u %>% filter(category == 'pass') , aes(x = mean, y = percent_zero, color = 'Splatter Simulation'), alpha = 0.08, size = 1.5) +
  #geom_point(data = realData2, aes(x = mean, y = percent_zero, color = 'In-house Simulation'), alpha = 0.08, size = 0.5) +
  ggtitle('') +
  labs(x = 'non-zero mean', y = '% zeros', color = 'Legend') +
  scale_color_manual(values = colors) +
  theme_classic() +
  theme(legend.position = c(0.8, 0.7))


P2 = ggplot(data = realData %>% filter(category == 'pass') , aes(x = mean, y = mean_real)) +
  geom_point(aes(color = 'Real Data'), alpha = 0.08, size = 0.5) +
  geom_point(data = u %>% filter(category == 'pass') , aes(x = mean, y = mean_real, color = 'Splatter Simulation'), alpha = 0.08, size = 1.5) +
  #geom_point(data = realData2, aes(x = mean, y = mean_real, color = 'In-house Simulation'), alpha = 0.08, size = 0.5) +
  ggtitle('') +
  labs(x = 'non-zero mean', y = 'mean including zeros', color = 'Legend') +
  scale_color_manual(values = colors) +
  theme_classic() +
  theme(legend.position = c(0.8, 0.7))

P3 = ggplot(data = realData %>% filter(category == 'pass') , aes(x = mean_real, y = percent_zero)) +
  geom_point(aes(color = 'Real Data'), alpha = 0.08, size = 0.5) +
  geom_point(data = u %>% filter(category == 'pass') , aes(x = mean_real, y = percent_zero, color = 'Splatter Simulation'), alpha = 0.08, size = 1.5) +
  #geom_point(data = realData2, aes(x = mean_real, y = percent_zero, color = 'In-house Simulation'), alpha = 0.08, size = 0.5) +
  ggtitle('') +
  labs(x = 'mean including zeros', y = '% zeros', color = 'Legend') +
  scale_color_manual(values = colors) +
  theme_classic() +
  theme(legend.position = c(0.8, 0.7))


P4 = ggplot(data = realData %>% filter(category == 'pass') , aes(x = mean, y = sd)) +
  geom_point(aes(color = 'Real Data'), alpha = 0.08, size = 0.5) +
  geom_point(data = u %>% filter(category == 'pass') , aes(x = mean, y = sd, color = 'Splatter Simulation'), alpha = 0.08, size = 1.5) +
  #geom_point(data = realData2, aes(x = mean, y = sd, color = 'In-house Simulation'), alpha = 0.08, size = 0.5) +
  ggtitle('') +
  labs(x = 'non-zero mean', y = 'standard deviation of non-zero portion', color = 'Legend') +
  scale_color_manual(values = colors) +
  theme_classic() +
  theme(legend.position = c(0.8, 0.7))

figure = ggpubr::ggarrange(P1, P2, P3, P4, labels = c("A","B","C", "D"), ncol = 2, nrow = 2)
#figure = ggpubr::ggarrange(P1, P2, P3, P4, P5, P6, labels = c("A", "B", "C", "D", "E", "F"), ncol = 3, nrow = 2)
figure
```


```{r}
ggplot(data = u %>% filter(category == 'pass') , aes(x = mean, y = percent_zero, colour = factor(meta_var))) +
  geom_point(alpha = 0.08, size = 0.5) +
  ggtitle('') +
  theme_bw()

ggplot(data = u %>% filter(category == 'pass'), aes(x = factor(meta_var), y = mean)) +
  geom_violin(fill = 'red', alpha = 0.5) + 
  geom_violin(data =  realData %>% filter(category == 'pass'), aes(x = factor(meta_var), y = mean), fill = 'blue', alpha = 0.5) +
  theme_bw()

ggplot(data = u %>% filter(category == 'pass'), aes(x = factor(meta_var), y = percent_zero)) +
  geom_violin(fill = 'red', alpha = 0.5) + 
  geom_violin(data =  realData %>% filter(category == 'pass'), aes(x = factor(meta_var), y = percent_zero), fill = 'blue', alpha = 0.5) +
  theme_bw()
```


```{r}
df.diff = data.frame(symbol = u %>% filter(meta_var == 30) %>% pull(Symbol) , diff = u %>% filter(meta_var == 30) %>% pull(mean_nonzero) / u %>% filter(meta_var == 0) %>% pull(mean_nonzero), mod = rowData(simDR)$Model, fc = rowData(simDR)$DE_idx, pz = u %>% filter(meta_var == 30) %>% pull(percent_zero))
df.diff
```





```{r}
idx = 2535
df.de = data.frame(dataset  = rep('SplattDR', length(colData(simDR)$Dose)),
                dose = colData(simDR)$Dose,
                logcount = assays(simDR)$logcount[idx, ],
                batch = assays(simDR)$BatchCellMeans[idx, ],
                base = assays(simDR)$BaseCellMeans[idx, ],
                bcv = assays(simDR)$BCV[idx, ],
                cellmeans = assays(simDR)$CellMeans[idx, ],
                true = assays(simDR)$TrueCounts[idx, ]
                )

ggplot(data = df.de, aes(x = true, color = dose)) +
  #facet_wrap(~dose) +
  geom_density(size = 1.5) +
  theme_bw()

ggplot(data = df.de, aes(x = cellmeans, color = dose)) +
  #facet_wrap(~dose) +
  geom_density(size = 1.5) +
  theme_bw()

ggplot(data = df.de, aes(x = bcv, color = dose)) +
  #facet_wrap(~dose) +
  geom_density(size = 1.5) +
  theme_bw()

ggplot(data = df.de, aes(x = base, color = dose)) +
  #facet_wrap(~dose) +
  geom_density(size = 1.5) +
  theme_bw()

ggplot(data = df.de, aes(x = batch, color = dose)) +
  #facet_wrap(~dose) +
  geom_density(size = 1.5) +
  theme_bw()

ggplot(data = df.de, aes(x = logcount, color = dose)) +
  #facet_wrap(~dose) +
  geom_density(size = 1.5) +
  theme_bw()

ggplot(data = df.de %>% filter(logcount > 0), aes(x = logcount, color = dose)) +
  #facet_wrap(~dose) +
  geom_density(size = 1.5) +
  theme_bw()
```


```{r fig.height = 12, fig.width = 6}
nonzeromeans = u[,c('Symbol', 'meta_var', 'mean_nonzero')]
is.na(nonzeromeans$mean_nonzero) = 0
wide = reshape2::dcast(nonzeromeans, Symbol ~  meta_var)
rownames(wide) = wide$Symbol
wide = wide[rownames(rowData(simDR)), ]
wide2 = wide[,3:10]
for (i in 2:8){
  wide2[,i] = wide2[i]/wide2[1]
}
plot(log(c(0,0.01, 0.03, 0.1, 0.3, 1, 3, 10, 30)), log(wide2[13, 1:9], 2), type = 'l', lwd = 1.4, ylim = c(-2,2))
for (gene in data.frame(rowData(simDR)) %>% filter(Model == 'ExpB') %>% pull(Gene)){
  lines(log(c(0,0.01, 0.03, 0.1, 0.3, 1, 3, 10, 30)), log(wide2[gene, 1:9],2))
}
```

```{r fig.height = 6, fig.width = 6}
plot(log(c(0,0.01, 0.03, 0.1, 0.3, 1, 3, 10, 30)), (wide2[idx, 1:9]), type = 'l', lwd = 3)
```


```{r}
mdls = data.frame(unlist(simDR@metadata$modelFits))
mdls$gene.par = rownames(mdls)
g = mdls %>% separate(gene.par, c("Gene","Par"))
new.metrics = spread(g, key = 'Par', value = unlist.simDR.metadata.modelFits.)
```


```{r}
new.metrics %>% filter(!is.na(k))
```

```{r}
idx2 = 108
control = assays(simDR)$logcount[idx2,which(colData(simDR)$Dose == 0)]
treated1 = assays(simDR)$logcount[idx2,which(colData(simDR)$Dose == 0.01)]
treated2 = assays(simDR)$logcount[idx2,which(colData(simDR)$Dose == 0.03)]
treated3 = assays(simDR)$logcount[idx2,which(colData(simDR)$Dose == 0.1)]
treated4 = assays(simDR)$logcount[idx2,which(colData(simDR)$Dose == 0.3)]
treated5 = assays(simDR)$logcount[idx2,which(colData(simDR)$Dose == 1)]
treated6 = assays(simDR)$logcount[idx2,which(colData(simDR)$Dose == 3)]
treated7 = assays(simDR)$logcount[idx2,which(colData(simDR)$Dose == 10)]
treated8 = assays(simDR)$logcount[idx2,which(colData(simDR)$Dose == 30)]
wilcox.test(control, treated1)
wilcox.test(control, treated2)
wilcox.test(control, treated3)
wilcox.test(control, treated4)
wilcox.test(control, treated5)
wilcox.test(control, treated6)
wilcox.test(control, treated7)
wilcox.test(control, treated8)
```

```{r}
head(rowData(simDR))
head(colData(simDR))
dim(assays(simDR)$logcount)
assays(simDR)$logcount[1:10,1:10]
```

```{r}
write.table(rowData(simDR), file = 'geneMeta_splattdr.txt', quote = FALSE, sep = '\t')
write.table(colData(simDR), file = 'cellMeta_splattdr.txt', quote = FALSE, sep = '\t')
write.table(assays(simDR)$logcount, file = 'normexp_splattdr.txt', quote = FALSE, sep = '\t')
```

```{r}
doses = as.numeric(as.matrix(data.frame(colData(simDR))$Dose))
DRTEST = rbind(doses, assays(simDR)$logcount[1:200,])

write.table(DRTEST, file = 'normexp_splattdr_short.txt', quote = FALSE, sep = '\t')

write.table(wide2, file = 'normexp_wide3.txt', quote = FALSE, sep = '\t')
```



```{r}
simData = list(norm = assays(simDR)$logcount, meta = data.frame(barcode = colData(simDR)$Cell, Dose = colData(simDR)$Dose))
u = rbind(
  realParams(simData, 4, metacol = 'Dose', metacriteria = 0, funpath = source_path),
  realParams(simData, 4, metacol = 'Dose', metacriteria = 0.01, funpath = source_path),
  realParams(simData, 4, metacol = 'Dose', metacriteria = 0.03, funpath = source_path),
  realParams(simData, 4, metacol = 'Dose', metacriteria = 0.1, funpath = source_path),
  realParams(simData, 4, metacol = 'Dose', metacriteria = 0.3, funpath = source_path),
  realParams(simData, 4, metacol = 'Dose', metacriteria = 1, funpath = source_path),
  realParams(simData, 4, metacol = 'Dose', metacriteria = 3, funpath = source_path),
  realParams(simData, 4, metacol = 'Dose', metacriteria = 10, funpath = source_path),
  realParams(simData, 4, metacol = 'Dose', metacriteria = 30, funpath = source_path)
)
```