---
title: "R Notebook"
output: html_notebook
---

## Setting up the environment and displaying session information for reproducibility
```{r}
library(doParallel, quietly = TRUE)
library(dplyr, quietly = TRUE)
library(tidyr, quietly = TRUE)
library(ggplot2, quietly = TRUE)
library(Seurat, quietly = TRUE)
library(scater, quietly = TRUE)
library(SingleCellExperiment, quietly = TRUE)
library(splatter, quietly = TRUE)
path1 = list.files('/mnt/home/naultran/SNSEQDATA_FINAL/splattDR/splattDR/R', full.names = TRUE)
path2 = list.files('/mnt/home/naultran/SNSEQDATA_FINAL/splattDR/splatter/R', full.names = TRUE)
sapply(path1, source)
sapply(path2, source)
sessionInfo()
```

# Estimate Splat parameters from each dose group of the hepatocyte cluster
```{r eval = TRUE}
params.list = readRDS('dr.param.list.RData')

splat.param = data.frame(matrix(NA, ncol = 32, nrow = 0))
colnames(splat.param) = names(attributes(params.list[[1]]))
for (name in names(params.list)){
  splat.param[name,] = attributes(params.list[[name]])
}
splat.param$cell.dose = rownames(splat.param)
splat.param = splat.param %>% separate(cell.dose, c("cell","dose"), sep = '_')

splat.long = reshape2::melt(splat.param[,c('cell', 'dose','mean.rate', 'mean.shape', 'out.prob', 'out.facLoc', 'out.facScale', 'bcv.common', 'bcv.df', 'dropout.mid', 'dropout.shape', 'lib.loc', 'lib.scale')], id.var = c('cell','dose'))

```


# Begin simulation of dose-response data
## Choose and set base splatter parameters object to initiate simulation
```{r}
simDR = list()
for (ct in unique(splat.long$cell)) {
  param.medians = splat.long %>% 
    group_by(cell, variable) %>% 
    summarize(median = median(value)) %>% 
    filter(cell == ct) %>% 
    spread(variable, median)
  for (de.prob in c(0.1)){
    for (facLoc in c(3)){
      for (i in 1:2){
        if (i == 1){
          dose.prob = rep(1/9, length(dose.names))
        } else {
          x = runif(9)
          dose.prob = x/sum(x)
        }
        vec_elem = paste(ct, de.prob, facLoc, paste(dose.prob, collapse=":"))
        print(vec_elem)
        
        params = newSplatParams()

        params@mean.rate = param.medians$mean.rate
        params@mean.shape = param.medians$mean.shape
        params@lib.loc = param.medians$lib.loc
        params@lib.scale = param.medians$lib.scale
        params@out.prob = param.medians$out.prob
        params@out.facLoc = param.medians$out.facLoc
        params@out.facScale = param.medians$out.facScale
        params@bcv.common = param.medians$bcv.common
        params@bcv.df = param.medians$bcv.df
        params@dropout.mid = param.medians$dropout.mid
        params@dropout.shape = param.medians$dropout.shape
        params@de.prob = de.prob
        params@de.facLoc = facLoc
        params@de.facScale = 0.8
        dose.names = c(0, 0.01, 0.03, 0.1, 0.3, 1, 3, 10, 30)
        params@nBatches = 1
        params@nCells = 500 * length(dose.names)
        params@nGenes = 22213
        
        simDR[[vec_elem]] = splatSimulateDR(params, method = 'doseresp', dose.names = dose.names, dose.prob = dose.prob, verbose = FALSE)
        saveRDS(simDR, file = 'simDR.batch.RData')
      }
    }
  }
}
```

```{r}
for (ct in unique(splat.long$cell)[c(1,2)]) {
  param.medians = splat.long %>% 
    group_by(cell, variable) %>% 
    summarize(median = median(value)) %>% 
    filter(cell == ct) %>% 
    spread(variable, median)
  for (de.prob in c(0.05, 0.1, 0.25, 0.5)){
    for (facLoc in c(0.1, 1, 3, 5)){
      for (i in 1:2){
        if (i == 1){
          dose.prob = rep(1/9, length(dose.names))
        } else {
          x = runif(9)
          dose.prob = x/sum(x)
        }
        vec_elem = paste(ct, de.prob, facLoc, paste(dose.prob, collapse=":"))
        print(vec_elem)
        
        params = newSplatParams()

        params@mean.rate = param.medians$mean.rate
        params@mean.shape = param.medians$mean.shape
        params@lib.loc = param.medians$lib.loc
        params@lib.scale = param.medians$lib.scale
        params@out.prob = param.medians$out.prob
        params@out.facLoc = param.medians$out.facLoc
        params@out.facScale = param.medians$out.facScale
        params@bcv.common = param.medians$bcv.common
        params@bcv.df = param.medians$bcv.df
        params@dropout.mid = param.medians$dropout.mid
        params@dropout.shape = param.medians$dropout.shape
        params@de.prob = de.prob
        params@de.facLoc = facLoc
        params@de.facScale = 0.8
        dose.names = c(0, 0.01, 0.03, 0.1, 0.3, 1, 3, 10, 30)
        params@nBatches = 1
        params@nCells = 500 * length(dose.names)
        params@nGenes = 22213
        
        simDR[[vec_elem]] = splatSimulateDR(params, method = 'doseresp', dose.names = dose.names, dose.prob = dose.prob, verbose = FALSE)
        saveRDS(simDR, file = 'simDR.batch.RData')
      }
    }
  }
}
```

```{r}
for (ct in unique(splat.long$cell)[c(3)]) {
  param.medians = splat.long %>% 
    group_by(cell, variable) %>% 
    summarize(median = median(value)) %>% 
    filter(cell == ct) %>% 
    spread(variable, median)
  for (de.prob in c(0.1)){
    for (ncell in c(50, 100, 500, 1000, 2000)){
      for (i in 1:2){
        if (i == 1){
          dose.prob = rep(1/9, length(dose.names))
        } else {
          x = runif(9)
          dose.prob = x/sum(x)
        }
        vec_elem = paste(ct, de.prob, facLoc, paste(dose.prob, collapse=":"))
        print(vec_elem)
        
        params = newSplatParams()

        params@mean.rate = param.medians$mean.rate
        params@mean.shape = param.medians$mean.shape
        params@lib.loc = param.medians$lib.loc
        params@lib.scale = param.medians$lib.scale
        params@out.prob = param.medians$out.prob
        params@out.facLoc = param.medians$out.facLoc
        params@out.facScale = param.medians$out.facScale
        params@bcv.common = param.medians$bcv.common
        params@bcv.df = param.medians$bcv.df
        params@dropout.mid = param.medians$dropout.mid
        params@dropout.shape = param.medians$dropout.shape
        params@de.prob = de.prob
        params@de.facLoc = 3
        params@de.facScale = 0.8
        dose.names = c(0, 0.01, 0.03, 0.1, 0.3, 1, 3, 10, 30)
        params@nBatches = 1
        params@nCells = ncell * length(dose.names)
        params@nGenes = 22213
        
        simDR[[vec_elem]] = splatSimulateDR(params, method = 'doseresp', dose.names = dose.names, dose.prob = dose.prob, verbose = FALSE)
        saveRDS(simDR, file = 'simDR.batch.RData')
      }
    }
  }
}
```